// MetalPetal Umbrella Header
// Auto Generated by `swift run main boilerplate-generator`

#import "MTIBuffer.h"
#import "MTICVMetalIOSurfaceBridge.h"
#import "MTICVMetalTextureBridging.h"
#import "MTICVMetalTextureCache.h"
#import "MTIComputePipeline.h"
#import "MTICorner.h"
#import "MTIError.h"
#import "MTIFunctionDescriptor.h"
#import "MTIGeometry.h"
#import "MTIImageProperties.h"
#import "MTILibrarySource.h"
#import "MTILock.h"
#import "MTIMemoryWarningObserver.h"
#import "MTIPixelFormat.h"
#import "MTIRenderPipeline.h"
#import "MTISamplerDescriptor.h"
#import "MTITextureDescriptor.h"
#import "MTITextureDimensions.h"
#import "MTITextureLoader.h"
#import "MTITexturePool.h"
#import "MTIVertex.h"
#import "MTIWeakToStrongObjectsMapTable.h"
#import "MTIShaderFunctionConstants.h"
#import "MTIShaderLib.h"

FOUNDATION_EXPORT double MetalPetalVersionNumber;
FOUNDATION_EXPORT const unsigned char MetalPetalVersionString[];
