// MetalPetal Umbrella Header
// Auto Generated by `swift run main boilerplate-generator`

#import "MTICorner.h"
#import "MTITextureDimensions.h"
#import "MTIShaderFunctionConstants.h"
#import "MTIShaderLib.h"

FOUNDATION_EXPORT double MetalPetalVersionNumber;
FOUNDATION_EXPORT const unsigned char MetalPetalVersionString[];
