// MetalPetal Umbrella Header
// Auto Generated by `swift run main boilerplate-generator`

#import "MTICVMetalIOSurfaceBridge.h"
#import "MTICVMetalTextureBridging.h"
#import "MTICVMetalTextureCache.h"
#import "MTICorner.h"
#import "MTIImageProperties.h"
#import "MTILibrarySource.h"
#import "MTILock.h"
#import "MTITextureDimensions.h"
#import "MTIShaderFunctionConstants.h"
#import "MTIShaderLib.h"

FOUNDATION_EXPORT double MetalPetalVersionNumber;
FOUNDATION_EXPORT const unsigned char MetalPetalVersionString[];
