//
//  BlendFormulaSupport.swift
//
//  Created by YuAo on 2021/2/6.
//

import Foundation

func generateBlendFormulaSupport(shadersDirectory: URL) throws -> String {
    let shaderHeaderContent = try String(
        contentsOf: shadersDirectory.appending(component: "MTIShaderLib.h"),
        encoding: .utf8
    )
    let functionConstantsContent = try String(
        contentsOf: shadersDirectory.appending(component: "MTIShaderFunctionConstants.h"),
        encoding: .utf8
    )
    return ##"""
    \##(autoGeneratedFileHeader)

    import Foundation

    private let shaderTemplate = #"""
    \##(shaderHeaderContent)
    \##(functionConstantsContent)

    using namespace metalpetal;

    {MTIBlendFormula}

    \##(generateBlendFilterFragmentShader(
        shaderFunctionName: "customBlend",
        blendFunctionName: "blend"
    ))

    \##(generateMultilayerCompositeFilterFragmentShader(
        shaderFunctionName: "multilayerCompositeCustomBlend",
        blendFunctionName: "blend"
    ))

    """#

    func MTIBuildBlendFormulaShaderSource(_ formula: String) -> String {
        #if targetEnvironment(simulator)
        let targetOSSimulator = 1
        #else
        let targetOSSimulator = 0
        #endif
        let hasTextureCoordinatesModifier = formula.contains("modify_source_texture_coordinates") ? 1 : 0
        let targetConditionals = """
            #ifndef TARGET_OS_SIMULATOR
            #define TARGET_OS_SIMULATOR \(targetOSSimulator)
            #endif\n\n#define MTI_CUSTOM_BLEND_HAS_TEXTURE_COORDINATES_MODIFIER \(hasTextureCoordinatesModifier)

            """
        return shaderTemplate
            .replacingOccurrences(of: "{MTIBlendFormula}", with: targetConditionals + formula)
    }

    """##
}
