//
//  BoilerplateGenerator.swift
//
//
//  Created by YuAo on 2020/3/16.
//

import Foundation

let autoGeneratedFileHeader = """
//
// This is an auto-generated source file.
//
"""

func generateBoilerplateFiles(projectRoot: URL) throws {
    let sourceDirectory = projectRoot.appending(path: "Sources/MetalPetal/")
    let generatedDirectory = sourceDirectory.appending(component: "Generated")
    let shadersDirectory = sourceDirectory.appending(component: "Shaders")
    try write(generateMtiVectorSimd(), to: generatedDirectory, as: "MTIVector+SIMD.swift")
    try write(generateMtiSimdArgumentValue(), to: generatedDirectory, as: "MTISIMDArgumentValue.swift")
    try write(
        generateBlendFormulaSupport(shadersDirectory: shadersDirectory),
        to: generatedDirectory,
        as: "MTIBlendFormulaSupport.swift"
    )
    try write(generateBlendingShaders(), to: shadersDirectory, as: "BlendingShaders.metal")
    try write(
        generateMultilayerCompositeShaders(),
        to: shadersDirectory,
        as: "MultilayerCompositeShaders.metal"
    )
}

private func write(_ content: String, to directory: URL, as file: String) throws {
    try content.write(to: directory.appending(component: file), atomically: true, encoding: .utf8)
}
