//
//  MTISIMDArgumentValue.swift
//
//
//  Created by YuAo on 2020/7/11.
//

import Foundation
import SIMDType

private struct ArgumentCase {
    let name: String
    let swiftType: String
    let dataType: String
    let availability: String?

    init(simdType: SIMDType) {
        name = simdType.unprefixedName
        swiftType = simdType.argumentValueTypeName
        dataType = simdType.unprefixedName
        availability = nil
    }

    init(name: String, swiftType: String, dataType: String, availability: String?) {
        self.name = name
        self.swiftType = swiftType
        self.dataType = dataType
        self.availability = availability
    }
}

private let argumentCases = SIMDType.metalSupportedSIMDTypes.map(ArgumentCase.init(simdType:)) + [
    ArgumentCase(
        name: "packedFloat3",
        swiftType: "MTLPackedFloat3",
        dataType: "float3",
        availability: "!os(tvOS)"
    ),
]

private func section(_ body: (ArgumentCase) -> String) -> String {
    argumentCases.map { argumentCase in
        guard let availability = argumentCase.availability else {
            return body(argumentCase)
        }
        return "#if \(availability)\n\(body(argumentCase))\n#endif"
    }.joined(separator: "\n")
}

func generateMtiSimdArgumentValue() -> String {
    let cases = section { "case \($0.name)(\($0.swiftType))" }
    let dataTypes = section { "case .\($0.name):\n.\($0.dataType)" }
    let bytes = section { "case let .\($0.name)(value):\ntry Swift.withUnsafeBytes(of: value, body)" }
    return """
    \(autoGeneratedFileHeader)

    import Foundation
    import Metal
    import simd

    public enum MTISIMDArgumentValue {
    \(cases)

        public var dataType: MTLDataType {
            switch self {
    \(dataTypes)
            }
        }

        public func withUnsafeBytes<R>(_ body: (UnsafeRawBufferPointer) throws -> R) rethrows -> R {
            switch self {
    \(bytes)
            }
        }
    }

    """
}
