import Foundation
import SIMDType

func generateMtiVectorSimd() -> String {
    var members: [String] = []
    for type in SIMDType.metalSupportedSIMDTypes {
        let swiftType = type.swiftSIMDTypeName
        let scalarType = type.scalarType.swiftTypeName
        let size = "MemoryLayout<\(swiftType)>.size"
        members.append("""
        public init(value: \(swiftType)) {
            var v = value
            let count = \(size) / MemoryLayout<\(scalarType)>.size
            let scalars = Swift.withUnsafeBytes(of: &v) { Array($0.bindMemory(to: \(scalarType).self)) }
            self.init(\(type.scalarValuesInitializerLabel): scalars, count: count)
        }

        public func \(type.unprefixedName)() -> \(swiftType) {
            var value = \(swiftType)()
            if scalarType == .\(type.scalarTypeCaseName) && byteLength == \(size) {
                withUnsafeBytes { source in
                    _ = Swift.withUnsafeMutableBytes(of: &value) {
                        memcpy($0.baseAddress!, source.baseAddress!, \(size)) }
                }
            }
            return value
        }
        """)
    }
    return """
    \(autoGeneratedFileHeader)

    import Foundation
    import simd

    extension MTIVector {

    \(members.joined(separator: "\n\n"))
    }
    """
}
